version: '3.8'

services:
  music-locker:
    build: .
    ports:
      - "8080:80"
    container_name: community-music-locker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
